openapi: 3.0.0
tags:
  - name: List
    description: List of resource instances.
  - name: Create
    description: Create resource
info:
  title: echo
  version: '1.0'
  contact:
    name: Pablo
  description: Echo API
servers:
  - url: 'http://localhost:3000'
paths:
  /endpoints:
    parameters: []
    get:
      tags:
        - List
      summary: List
      operationId: get-endpoints
      responses:
        '200':
          description: OK
          content:
            application/vdn.api+json:
              schema:
                description: ''
                type: object
                properties:
                  data:
                    type: array
                    uniqueItems: true
                    items:
                      type: object
                      properties:
                        type:
                          type: string
                          minLength: 1
                        id:
                          type: string
                          minLength: 1
                        attributes:
                          type: object
                          properties:
                            verb:
                              type: string
                              minLength: 1
                            path:
                              type: string
                              minLength: 1
                            response:
                              type: object
                              required:
                                - code
                              properties:
                                code:
                                  type: number
                                headers:
                                  type: object
                                body:
                                  type: string
                                  minLength: 1
                          required:
                            - verb
                            - path
                            - response
                      required:
                        - type
                        - id
                required:
                  - data
              examples:
                Show endpoint response:
                  value:
                    data:
                      - type: endpoints
                        id: '12345'
                        attributes:
                          verb: GET
                          path: /greeting
                          response:
                            code: 200
                            headers: {}
                            body: '"{ "message": "Hello, world" }"'
      description: List the endpoints
    post:
      summary: ''
      operationId: post-endpoints
      description: Create endpoint
      requestBody:
        content:
          application/vnd.api+json:
            schema:
              description: ''
              type: object
              properties:
                data:
                  type: object
                  required:
                    - type
                  properties:
                    type:
                      type: string
                      minLength: 1
                    attributes:
                      type: object
                      required:
                        - verb
                        - path
                        - response
                      properties:
                        verb:
                          type: string
                          minLength: 1
                        path:
                          type: string
                          minLength: 1
                        response:
                          type: object
                          required:
                            - code
                            - body
                          properties:
                            code:
                              type: number
                            headers:
                              type: object
                            body:
                              type: string
                              minLength: 1
              required:
                - data
            examples:
              Create meeting request body:
                value:
                  data:
                    type: endpoints
                    attributes:
                      verb: GET
                      path: /greeting
                      response:
                        code: 200
                        headers: {}
                        body: '"{ "message": "Hello, world" }"'
      responses:
        '201':
          description: Created
          content:
            application/vdn.api+json:
              schema:
                description: ''
                type: object
                properties:
                  data:
                    type: object
                    required:
                      - type
                      - id
                      - attributes
                    properties:
                      type:
                        type: string
                        minLength: 1
                      id:
                        type: string
                        minLength: 1
                      attributes:
                        type: object
                        required:
                          - verb
                          - path
                          - response
                        properties:
                          verb:
                            type: string
                            minLength: 1
                          path:
                            type: string
                            minLength: 1
                          response:
                            type: object
                            required:
                              - code
                              - headers
                              - body
                            properties:
                              code:
                                type: number
                              headers:
                                type: object
                              body:
                                type: string
                                minLength: 1
                required:
                  - data
              examples:
                Create endpoint response:
                  value:
                    data:
                      type: endpoints
                      id: '12345'
                      attributes:
                        verb: GET
                        path: /greeting
                        response:
                          code: 200
                          headers: {}
                          body: '"{ "message": "Hello, world" }"'
        '422':
          description: Unprocessable Entity (WebDAV)
          headers: {}
          content:
            application/vdn.api+json:
              schema:
                type: object
                properties:
                  errors:
                    type: array
                    items:
                      type: object
                      properties:
                        status:
                          type: string
                        source:
                          type: object
                          properties:
                            pointer:
                              type: string
                        title:
                          type: string
                        detail:
                          type: string
      tags:
        - Create
components:
  schemas: {}
  securitySchemes:
    authorization:
      name: Bearer <token>
      type: apiKey
      in: header
  examples: {}
security:
  - authorization: []
